import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import fetch from 'node-fetch'; 
import Replicate from 'replicate';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const CLOSET_FILE = path.join(__dirname, 'closet.json');

const app = express();
const PORT = 3001;

const replicate = new Replicate({
  auth: process.env.REPLICATE_API_TOKEN,
});

app.use(cors());
// Need a larger limit for base64 image strings
app.use(express.json({ limit: '50mb' })); 

app.post('/api/analyze', async (req, res) => {
  const { prompt, images, includeContext } = req.body;

  try {
    const base64Image = images[0];

    let augmentedPrompt = prompt || 'What clothes should I wear based on how I look?';

    if (includeContext) {
      try {
        const items = await readCloset();
        const closetContext = items.length > 0
          ? items.map(i => `- ${i.type}: ${i.description}`).join('\n')
          : "Digital Closet is currently empty.";

        let weather = "Unknown weather";
        try {
          // Using explicit location (Boulder, CO) for accurate weather with Fahrenheit
          const wRes = await fetch('https://wttr.in/Boulder,CO?format="%C,+%t,+Humidity:+%h,+Wind:+%w"&u');
          if (wRes.ok) {
            weather = (await wRes.text()).replace(/"/g, '').trim();
          }
        } catch (e) {
          console.error("Weather fetch failed:", e);
        }

        augmentedPrompt = `${augmentedPrompt}\n\nFor reference, here is some optional background context you may use if relevant to the question:\n- Today's Weather in Boulder, CO: ${weather}\n- Digital Closet Contents:\n${closetContext}\n\nIMPORTANT: Answer the user's question directly. If they ask what they are wearing, describe what you see. If they ask for outfit suggestions, pick ONE best outfit from the closet items above based on the weather. Be concise.`;
      } catch (e) {
        console.error("Failed to build context:", e);
      }
    }

    const ollamaRequestBody = {
      model: 'llava', // Reverted to a true vision model so it can actually see the image
      prompt: augmentedPrompt,
      images: [base64Image],
      stream: false,
      options: {
        num_predict: 100, // Increased slightly to allow a full sentence
        temperature: 0.1 // Keep temperature low for faster, deterministic responses
      }
    };

    const response = await fetch('http://localhost:11434/api/generate', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(ollamaRequestBody),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Ollama API error ${response.status}: ${errorText}`);
    }

    const data = await response.json();
    
    // Ollama returns { response: "text here..." } directly
    const aiText = data.response || "Could not identify clothing.";

    // Send it back to the React frontend matching the expected schema `{ response: "..." }`
    res.json({ response: aiText }); 
  } catch (err) {
    console.error('Backend Error talking to Ollama:', err);
    res.status(500).json({ error: 'Failed to communicate with Local Ollama backend: ' + err.message });
  }
});

// New Endpoint for Replicate Image Generation (Clothing Swap / Inpainting)
app.post('/api/generate-outfit', async (req, res) => {
  const { prompt, images } = req.body;
  
  if (!process.env.REPLICATE_API_TOKEN) {
    return res.status(500).json({ error: 'REPLICATE_API_TOKEN is not set in the .env file.' });
  }

  try {
    // Replicate usually expects images as a Data URI (with mime type), so we format it
    // The frontend sends base64 (without the prefix string), so we add it back for Replicate.
    const imageUri = `data:image/jpeg;base64,${images[0]}`;

    // Using the highly stable classic Stable Diffusion 1.5 image-to-image model which has a definitive accessible hash
    const output = await replicate.run(
      "stability-ai/stable-diffusion:ac732df83cea7fff18b8472768c88ad041fa750ff7682a21affe81863cbe77e4",
      {
        input: {
          image: imageUri,
          prompt: `A beautiful person wearing ${prompt || 'a stylish new outfit'}, high quality, realistic, beautiful photography, detailed clothing`,
          prompt_strength: 0.75, // Higher strength gives the AI more freedom to draw the new outfit
          num_outputs: 1,
          guidance_scale: 7.5,
        }
      }
    );

    // Replicate returns an array of image URLs
    console.log('Replicate finished!', output);
    if (output && output.length > 0) {
      res.json({ imageUrl: output[0] });
    } else {
      throw new Error("No image generated by Replicate");
    }

  } catch (err) {
    console.error('Backend Error talking to Replicate:', err);
    res.status(500).json({ error: 'Failed to generate outfit with Replicate: ' + err.message });
  }
});

// Helper to reliably read the closet
async function readCloset() {
  try {
    const data = await fs.readFile(CLOSET_FILE, 'utf-8');
    return JSON.parse(data);
  } catch (err) {
    // If file doesn't exist yet, return empty array
    if (err.code === 'ENOENT') {
      return [];
    }
    throw err;
  }
}

// Helper to write to closet
async function writeCloset(data) {
  await fs.writeFile(CLOSET_FILE, JSON.stringify(data, null, 2), 'utf-8');
}

// GET all closet items
app.get('/api/closet', async (req, res) => {
  try {
    const items = await readCloset();
    res.json(items);
  } catch (err) {
    console.error('Error reading closet:', err);
    res.status(500).json({ error: 'Failed to read closet.' });
  }
});

// POST new closet item
app.post('/api/closet', async (req, res) => {
  const { imageUrl, description, type, category } = req.body;
  if (!imageUrl || !type) {
    return res.status(400).json({ error: 'Image URL and type are required' });
  }

  try {
    const items = await readCloset();
    const newItem = {
      id: Date.now().toString(),
      imageUrl,
      description: description || '',
      type,
      category: category || 'Casual',
      dateAdded: new Date().toISOString()
    };
    items.unshift(newItem); // Add to beginning of array
    await writeCloset(items);
    res.json(newItem);
  } catch (err) {
    console.error('Error adding to closet:', err);
    res.status(500).json({ error: 'Failed to add item to closet.' });
  }
});

// DELETE closet item
app.delete('/api/closet/:id', async (req, res) => {
  const { id } = req.params;
  try {
    const items = await readCloset();
    const newItems = items.filter(item => item.id !== id);
    if (items.length === newItems.length) {
      return res.status(404).json({ error: 'Item not found' });
    }
    await writeCloset(newItems);
    res.json({ success: true, message: 'Item deleted' });
  } catch (err) {
    console.error('Error deleting item from closet:', err);
    res.status(500).json({ error: 'Failed to delete item.' });
  }
});

// ElevenLabs Text-to-Speech proxy
app.post('/api/tts', async (req, res) => {
  const { text } = req.body;
  const apiKey = process.env.ELEVENLABS_API_KEY;

  if (!apiKey) {
    return res.status(500).json({ error: 'ELEVENLABS_API_KEY is not set in .env' });
  }

  if (!text || text.trim().length === 0) {
    return res.status(400).json({ error: 'No text provided for speech synthesis' });
  }

  try {
    // Using "Rachel" voice (21m00Tcm4TlvDq8ikWAM)
    const voiceId = '21m00Tcm4TlvDq8ikWAM';
    const ttsResponse = await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${voiceId}`, {
      method: 'POST',
      headers: {
        'xi-api-key': apiKey,
        'Content-Type': 'application/json',
        'Accept': 'audio/mpeg'
      },
      body: JSON.stringify({
        text: text.substring(0, 500), // Limit text length to save API credits
        model_id: 'eleven_flash_v2_5',
        voice_settings: {
          stability: 0.5,
          similarity_boost: 0.75
        }
      })
    });

    if (!ttsResponse.ok) {
      const errorText = await ttsResponse.text();
      throw new Error(`ElevenLabs API error ${ttsResponse.status}: ${errorText}`);
    }

    // Stream the audio bytes back to the frontend
    res.set('Content-Type', 'audio/mpeg');
    const arrayBuffer = await ttsResponse.arrayBuffer();
    res.send(Buffer.from(arrayBuffer));
  } catch (err) {
    console.error('TTS Error:', err);
    res.status(500).json({ error: 'Text-to-speech failed: ' + err.message });
  }
});

app.listen(PORT, () => {
  console.log(`Backend server is running on http://localhost:${PORT}`);
});
